# demo
global_settings:
  # logging 配置
  logging:
    log_dir: /path/to/logs  # 日志目录
    level: info  # 日志级别，可选值：debug, info, warning, error, critical
    console_level: info  # 控制台日志级别
    file_level: DEBUG  # 文件日志级别

  # Ray 配置
  ray:
    num_cpus: 8 
    temp_dir: /tmp/ray  # Ray 临时目录

  # paths
  paths:
    original_alpha_data_path: /path/to/original/data  # 原始数据路径
    code_recorded_path: /path/to/code/recorded  # 代码模板路径
    backtest_path: /path/to/backtest  # 回测代码生成路径
    demo_path: /path/to/demo  # 配置模板路径
    backtest_path: /path/to/backtest  # 回测代码生成路径
    data_dir: /path/to/data  # 数据目录
    config_dir: /path/to/config  # 配置目录

  # ic params:
  ic_params:
    ret_path: /path/to/returns  # 收益率数据路径
    window: 20  # 窗口大小
    min_ic: 0.015  # 最小信息系数
    min_rank_ic: 0.015  # 最小排名信息系数

  # other settings
  default_batch_size: 20  # 批处理大小，用于 load_nested_dict 和 compute_ic


# functions settings
function_settings:
  # level1_functions: 一级函数列表
  # level2_functions: 二级函数列表
  # processorfilter_params: 过滤器参数配置
  # filter_params: 滤波器参数配置
  level1_functions:
    section_funcs:
      - diff # numpy/torch 0.002
      - apo # numpy/torch 0.003
      - abs_v # numpy/torch 0.001
      - sigmoid # numpy/torch 0.003
      - exp # numpy 0.001
      - tan # numpy 0.001
      - sin # numpy 0.009
      - cos # numpy 0.007
      - asin # numpy 0.001
      - acos # numpy 0.003
      - atan # numpy 0.001
      - lg1p # numpy 0.002
      - sinh # numpy/torch 0.002
      - cosh # numpy/torch 0.002
      - tanh # numpy/torch 0.002
      - reciprocal # numpy 0.002
      - sec_zsc # numpy 0.003
      - pct_rank # numpy 0.02
      - bin # numpy 0.004
      - binshannon # Todo: 
      - trewgt # numpy 0.002
      - revwgt # numpy 0.008
      - trerevwgt # numpy 0.006
    ts_funcs:
      filt_funcs:
        - fft_amp # numpy/ torch 0.004
        - fft_angle # numpy 0.009
        - fft_r # numpy/ torch 0.007
        - dwt_ca_fver # torch 0.06
        - dwt_da_fver # torch 0.06
        - savgolfilt # torch 0.005
        - medfilt # numpy 0.06
        - lowpfilt # torch 0.005
        - highpfilt # torch 0.006
        - bandpfilt # torch 0.009
        - wdfilt # torch / numpy 0.11
        - hpfilt # torch / numpy 0.09
        - rob_zsfilt # torch 0.003
        - rollrankfilt # pandas 0.28
        - ewma # torch 0.003
        - kalfilt # numpy 26
        - hb_insphase # numpy 0.03
        - kauama # numpy 0.015
        - mesama # numpy 0.011
      expand_funcs:
        - expandmean # torch 0.003
        - expandmax # numpy 0.001
        - expandmin  # numpy 0.003
        - expandzscore # torch 0.003
        - expandstd # numpy 0.003
        - expandskew # pandas 0.06
        - expandkurt # pandas 0.06
        - expandsum # numpy 0.002
      roll_funcs:
        - aroonosc # torch 0.006
        - rollmean # torch 0.003
        - rollmax # torch 0.009
        - rollmin # torch 0.002
        - rollzscore # torch 0.007
        - rollstd # torch 0.003
        - rollskew # torch 0.03
        - rollkurt # torch 0.03
        - rollsum # torch 0.004
          
  level2:
    - quantile_25
    - mean
    - quantile_75
    - skew
    - kurt
    - cv
    - ptp
    - sum
    - stddev
    - bop

  # filter functions_params
  filter_params:
    level1:
      shrink_factor: 1.0  # 用于标准化数据，防止数值溢出
      inf_handling:
        axis: 0  # 处理无穷大值的轴（0 为时间轴，1 为横截面轴）
      filters:  # 过滤器参数配置
        dwt_ca_fixed:
          wavelet: db1  # 离散小波变换使用的 wavelet 类型
        dwt_da_fixed:
          wavelet: db1
        dwt_ca:
          wavelet: db1
          level: 1
        dwt_da:
          wavelet: db1
          level: 1
        savgol_filter:
          window_length: 5
          polyorder: 2
        median_filter:
          size: 5
        lowpass_filter:
          cutoff: 0.1
          fs: 1
          order: 5
        highpass_filter:
          cutoff: 0.1
          fs: 1
          order: 5
        butter_highpass_filter:
          cutoff: 0.1
          fs: 1
          order: 5
        bandpass_filter:
          lowcut: 0.1
          highcut: 0.5
          fs: 1
          order: 5
        wavelet_denoise:
          wavelet: db4
          level: 1
          mode: soft
        ewma_filter:
          span: 10
        kalman_filter:
          transition_covariance: 0.01
          observation_covariance: 0.1
        hp_filter:
          lamb: 1600
        robust_zscore_filter:
          threshold: 3.0
        rolling_rank_filter:
          window: 5
        kaufman_adaptive_moving_average:
          fast_period: 2
          slow_period: 10
        mesa_adaptive_moving_average:
          fast_period: 2
          slow_period: 10
        # heikin_ashi_insphase:
          # period: 14  # Heikin-Ashi 指标的周期

# # 过滤参数
# filter_params:
#   level1:
#     windows: [2, 5, 7]  # 窗口大小列表，用于 group_data_by_window 和 process_level1
#     fill_methods: [null, fill_cross_sectional_mean, ffill]  # 数据填充方法
#   level2:
#     smoothing_methods: [quantile_25, mean, quantile_75, skew, kurt, cv, ptp, sum, stddev]  # 平滑方法列表

experiments:
  - id: "exp1" # represents the factor name
    active: true
    data_params: # suffix for data parameters
      - 5
      - 15
      - 30_b10_d1
      - 60_b20_d1
    
  - id: "exp2"
    active: true
    data_params:
      - 5
      - 15
      - 30_b10_d1
      - 60_b20_d1
    
  



# experiments:
#   - id: "experiment_1"
#     description: "First experiment with basic settings"
#     data_params:
#       table_name: "moneyflow_data"
#       table_type: "moneyflow"
#       table_freq: "15"
#     func_params:
#       level1:
#       rolling_para: [2, 5, 7]  # 窗口大小列表
#       func_list:
#         - diff # numpy/torch 0.002
#         - apo # numpy/torch 0.003
#         - abs_v # numpy/torch 0.001
#         - sigmoid # numpy/torch 0.003
#         - exp # numpy 0.001
#         - tan # numpy 0.001
#         - sin # numpy 0.009
#         - cos # numpy 0.007
#         - asin # numpy 0.001
#         - acos # numpy 0.003
#         - atan # numpy 0.001
#         - lg1p # numpy 0.002
#         - sinh # numpy/torch 0.002
#         - cosh # numpy/torch 0.002
#         - tanh # numpy/torch 0.002
#         - reciprocal # numpy 0.002
#         - sec_zsc # numpy 0.003
#         - pct_rank # numpy 0.02
#         - bin # numpy 0.004
#         - binshannon # Todo: 
#         - trewgt # numpy 0.002
#         - revwgt # numpy 0.008
#         - trerevwgt # numpy 0.006

#         - fft_amp # numpy/ torch 0.004
#         - fft_angle # numpy 0.009
#         - fft_r # numpy/ torch 0.007
#         - dwt_ca_fver # torch 0.06
#         - dwt_da_fver # torch 0.06
#         - savgolfilt # torch 0.005
#         - medfilt # numpy 0.06
#         - lowpfilt # torch 0.005
#         - highpfilt # torch 0.006
#         - bandpfilt # torch 0.009
#         - wdfilt # torch / numpy 0.11
#         - hpfilt # torch / numpy 0.09
#         - rob_zsfilt # torch 0.003
#         - rollrankfilt # pandas 0.28
#         - ewma # torch 0.003
#         - kalfilt # numpy 26
#         - hb_insphase # numpy 0.03
#         - kauama # numpy 0.015
#         - mesama # numpy 0.011
        
#         - expandmean # torch 0.003
#         - expandmax # numpy 0.001
#         - expandmin  # numpy 0.003
#         - expandzscore # torch 0.003
#         - expandstd # numpy 0.003
#         - expandskew # pandas 0.06
#         - expandkurt # pandas 0.06
#         - expandsum # numpy 0.002

#         - aroonosc # torch 0.006
#         - rollmean # torch 0.003
#         - rollmax # torch 0.009
#         - rollmin # torch 0.002
#         - rollzscore # torch 0.007
#         - rollstd # torch 0.003
#         - rollskew # torch 0.03
#         - rollkurt # torch 0.03
#         - rollsum # torch 0.004
        
#       level2:
#       func_list:
#         - quantile_25
#         - mean
#         - quantile_75
#         - skew
#         - kurt
#         - cv
#         - ptp
#         - sum
#         - stddev
#         - bop
#     active: true

#     - name: "experiment_2"
#     description: "Second experiment with modified parameters"
#     data_params:
#       table_name: "moneyflow_data"
#       table_type: "moneyflow"
#       table_freq: "30"
#     func_params:
#       func_name: "process_moneyflow_data"
#       func_type: "moneyflow"
#     active: true

#     - name: "experiment_3"
#     description: "Third experiment with further modifications"
#     data_params:
#       table_name: "moneyflow_data"
#       table_type: "moneyflow"
#       table_freq: "60"
#     func_params:
#       func_name: "process_moneyflow_data"
#       func_type: "moneyflow"
#     active: true
